# Harjoitus 4: Tavalliset ja materialisoidut näkymät

**Harjoituksen sisältö** - Harjoituksessa tutustutaan eri tyyppisten näkymien luontiin ja käyttöön

**Harjoituksen tavoite** - Harjoituksen opiskelija osaa luoda ja muokata näkymää, ja hänellä on käsitys näkymien käyttötarkoituksesta.

### Valmistautuminen

Avaa [pgAdmin](/pgadmin) selaimeen ja kirjaudu sisään. Avaa **Query Tool** (Valitse *trainingdatabase* **-\>** Ylhäältä **Tools** **-\>** **Query Tool**).

## Harjoitus: tavallinen näkymä

Muodosta puurekisteri-aineistosta näkymä "puut_kaupunginosittain", jossa on tieto myös siitä, missä kaupunginosassa puu on.

:::code-box
```sql
CREATE VIEW puut_kaupunginosittain AS (
SELECT

FROM
);

```
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">vinkki</button>

::: hidden-box
:::code-box
```sql
CREATE VIEW puut_kaupunginosittain AS (
    SELECT a.*, b.nimi_fi  
    FROM helsinki.___ a 
    JOIN helsinki.___ b 
    ON ... 
-- Millä ST-funktiolla spatiaalinen predikaatti, joka
-- palauttaa tosi kun puu tietyn kaupunginosan sisällä
);
```
:::
:::

<button onclick="toggleAnswer(this)" class="btn answer_btn">ratkaisu</button>

:::hidden-box
:::code-box
```sql
CREATE VIEW puut_kaupunginosittain AS (
    SELECT a.*, b.nimi_fi  
    FROM helsinki.puurekisteri_piste a 
    JOIN helsinki.kaupunginosajako b 
    ON ST_Within(a.wkb_geometry, b.wkb_geometry)
);
```
:::
:::



## Harjoitus 8.5: Geometrioiden yhdistäminen

Muodosta (yhdistä) hallintoalueista maakuntien raja -aineisto:

:::code-box
```sql

DROP TABLE IF EXISTS tmp.maakunnat;

CREATE TABLE tmp.maakunnat as (
    SELECT
    ST_Union(wkb_geometry), maaku_ni1 as "Maakunnan nimi"
    FROM
    nlsfi.hallintoalue
    GROUP BY
    maaku_ni1
);
```
:::

Vastaavasti, aineiston voi muodostaa myös hyödyntämällä näkymiä:

:::code-box
```sql
DROP VIEW IF EXISTS tmp.view_maakunta;

CREATE VIEW tmp.view_maakunta AS (
    SELECT
    ST_Union(wkb_geometry), maaku_ni1
    FROM
    nlsfi.hallintoalue
    GROUP BY
    maaku_ni1
);
```
:::


