# Harjoitus 8: Indeksit - tavalliset ja spatiaaliset

**Harjoituksen sisältö** Kyselyjen suorittamisen tutkinta, Query Planner, sekä indeksien luonti

**Harjoituksen tavoite** - Opiskelija tuntee indeksien luomisen ja käyttötavat 

### Valmistautuminen

Avaa [pgAdmin](/pgadmin) selaimeen ja kirjaudu sisään.  Avaa **Query Tool** (Valitse _trainingdatabase_ **->** Ylhäältä **Tools** **->** **Query Tool**).

## Harjoitus 8.1: PostgreSQL:n ei-spatiaaliset indeksit

### PostgreSQL:n Query Planner sekä EXPLAIN ANALYZE -komento

Kun SQL-kysely ajetaan, kysely menee ensimmäiseksi nk. Plannerille, suunnittelijalle, joka määrittää mikä on optimaalisin tapa toteuttaa annetun 
SQL-syntaksin mukainen kysely tietokannassa (esimerkiksi milloin tulisi käyttää määriteltyjä indeksejä ja milloin hakea vain taulusta rivi kerrallaan),
ja muokkaa kyselyä sen mukaan.

Olet ehkä huomannutkin että kun ajat PgAdminissa kyselyn ruudussa käväisee vihreä palkki, joka kertoo kuinka monta tietuetta kysely palautti mutta
myös sen, kuinka kauan kyselyyn kului aikaa millisekunteina. Vaikka tästä arvosta saakin osviittaa kyselyn kestosta, se sisältää myös esimerkiksi 
verkkoliikenteeseen kuluvan ajan ja ei siten ole kovin sopiva itse kyselyjen optimointia tarkasteltaessa. 

Tähän tarkoitukseen on olemassa komennot EXPLAIN sekä EXPLAIN ANALYZE. Näitä käytetään yksinkertaisesti kirjoittamalla kyseinen avainsana ennen varsinaista kyselyä. Nämä kaksi eroavat toisistaan 
siinä, että EXPLAIN-komennolla saa näkyviin Plannerin muodostaman suunnitelman kyselyn toteutuksesta, kun taas EXPLAIN ANALYZE suorittaa kyselyn ja 
palauttaa lisäksi tietoa itse suorituksen kestosta. Kestosta annetaan sekä suunnitelman tuottamiseen kulunut aika että (käytettäessä EXPLAIN ANALYZEä)
sen suorittamiseen kuluva aika millisekunteina, sekä kyselyn eri osien suhteellisia kustannuksia (Cost). 

On myös huomattava, että kumpikaan ei kuitenkaan 
palauta itse kyselyn tuottamia rivejä vaan ainoastaan tiedon siitä, millä tavoin kyselyä tultaisiin ajamaan.

Tarkastellaan tätä muutamien esimerkkikyselyiden avulla:

:::code-box
```sql

EXPLAIN ANALYZE SELECT * FROM helsinki.liikennevaylat;

```
:::


:::code-box
```sql

EXPLAIN ANALYZE SELECT * FROM helsinki.liikennevaylat WHERE pituus BETWEEN 50 AND 55;

```
:::

:::code-box
```sql

EXPLAIN ANALYZE SELECT * FROM helsinki.liikennevaylat WHERE pituus < 13;

```
:::

Luodaan sitten BTREE-indeksi kentälle "pituus". Lyhimmillään tämä käy komennolla

:::code-box
```sql

CREATE INDEX ON helsinki.liikennevaylat (pituus);

```
:::

Jos halutaan varmistua indeksin nimestä ja tyypistä, kirjoitetaan eksplisiittisesti

:::code-box
```sql

CREATE INDEX liikennevaylat_pituus_idx ON helsinki.liikennevaylat USING BTREE (pituus);

```
:::

Samaten indeksin poistaminen on helppoa:

:::code-box
```sql

DROP INDEX liikennevaylat_pituus_idx;

```
:::

Aja edellä annettuja kyselyjä ensin ilman indeksiä ja indeksin määrittelyn jälkeen (voit koittaa ajaa kyselyn muutaman kerran saadaksesi keskiarvon)







EXPLAIN ANALYZEn tuloksissa esiintyviä sanoja
- Seq Scan = sequential scanning, taulusta haetaan rivi kerrallaan
- Bitmap Heap Scan
- Bitmap Index Scan
- Heap Blocks
- Hash Join 

cost 
row 
width
actual time
loops

Katso tallennetun indeksin koko 

:::code-box
```sql

SELECT pg_size_pretty(pg_relation_size(‘users_username_idx’));

```
:::




Muut työkalut: https://explain.depesz.com/, https://explain.dalibo.com/ voi käyttää myös lokaalisti käytettävä versio, html-tiedosto?
 

## Harjoitus 8.2: PostgreSQL:n spatiaaliset indeksit


## Harjoitus 8.3: Taulutilat

Tarkista koulutuspalvelimen oletustaulutilojen sijainti. Käyttäjien tiedot sijaitsevat **pg_default**-taulutilassa, joka on data_directoryn base-hakemistossa. Järjestelmän yleiset tiedot sijaitsevat **pg_global**-taulutilassa, joka on data_directoryn global-hakemistossa. Datahakemiston sijainnin voit tarkistaa komennolla:

:::code-box
```sql
SHOW data_directory;
```
:::

## Harjoitus 8.4: Uuden taulutilan luominen

Uutta taulutilaa varten pitää luoda ensin palvelimelle kansio. Kansion tulee olla postgres-käyttäjän omistuksessa ja käyttöoikeudet vain postgres-käyttäjälle. Hakemisto on luotu valmiiksi palvelimelle komennoilla:

```
sudo mkdir /usr/local/tmp_tbls
sudo chown -R postgres:postgres /usr/local/tmp_tbls/
sudo chmod 700 /usr/local/tmp_tbls/
```

Luo uusi taulutila SQL-komennolla psql:n tai pgAdminin avulla:

:::code-box
```sql
CREATE TABLESPACE tmp_tablespace
LOCATION '/usr/local/tmp_tbls';
```
:::


## Harjoitus 8.5: Tietokannan ja taulun taulutilan muuttaminen

Koko tietokannan taulutilan voi muuttaa yhdellä komennolla.

:::hint-box
**HUOM!** Tätä ei kuitenkaan voi tehdä jos tietokantaan on auki aktiivisia yhteyksiä!
:::

1. Sulje pgAdminin tietokantayhteys harjoitustietokantaasi klikkaamalla tietokantaa sivupaneelissa hiiren oikealla painikkeella ja valitsemalla **Disconnect Database**.
2. Avaa tämän jälkeen sivupaneelista postgres-tietokanta ja avaa **Query tool** (voit tehdä tämän myös psql:n avulla). Anna komento:

:::code-box
```sql
ALTER DATABASE trainingdatabase
SET TABLESPACE tmp_tablespace;
```
:::

:::hint-box
Mikäli tämä ei onnistu, ja pgAdmin4 kertoo, että tietokantaan on aktiivisia yhteyksiä, yritä kirjautua ulos ja takaisin sisään pgAdminiin.
:::

Voit tarkistaa tietokannan taulutilan sijainnin SQL-kyselyllä:

:::code-box
```sql
SELECT
spcname, pg_tablespace_location(oid)
FROM
pg_tablespace;
```
:::

Luo testausta varten tilapäinen taulu:

:::code-box
```sql
DROP TABLE IF EXISTS tmp_table;

CREATE TABLE tmp_table AS
SELECT x
FROM
generate_series(2,5000,2) AS x;
```
:::

Taulun käyttämän taulutilan voit tarkistaa seuraavalla komennolla:

:::code-box
```sql
SELECT
tablename, tablespace
FROM
pg_tables
WHERE
tablename = 'tmp_table';
```
:::

Muuta taulun taulutilaa seuraavalla komennolla:

:::code-box
```sql
ALTER TABLE
tmp_table
SET TABLESPACE
tmp_tablespace;
```
:::

Tarkista, että taulun taulutila on nyt muuttunut. Voit myös käyttää pgAdminin käyttöliittymää taulutilojen tarkastamiseen.

## Harjoitus 8.6: Indeksin taulutilan muuttaminen

Voit luoda indeksin tauluun komennolla:

:::code-box
```sql
CREATE INDEX
idx_tmp_x
ON tmp_table(x);
```
:::

Indeksit luodaan oletusarvoisesti **pg_default**-taulutilaan. Usein käytetyt indeksit voi olla tarpeen tallentaa sellaiseen taulutilaan, joka käyttää palvelimessa olevaa nopeinta levyä (esimerkiksi SSD-levyt). Indeksien taulutilan muuttaminen onnistuu seuraavasti:

:::code-box
```sql
ALTER INDEX
idx_tmp_x
SET TABLESPACE
tmp_tablespace;
```
:::

