# Harjoitus 9: Indeksit - tavalliset ja spatiaaliset

**Harjoituksen sisältö** - 

**Harjoituksen tavoite** - Opiskelija tuntee PostgreSQL:n 

### Valmistautuminen

Avaa [pgAdmin](/pgadmin) selaimeen ja kirjaudu sisään.  Avaa **Query Tool** (Valitse _trainingdatabase_ **->** Ylhäältä **Tools** **->** **Query Tool**).

## PostgreSQL:n ei-spatiaaliset indeksit

### PostgreSQL:n Query Planner sekä EXPLAIN ANALYZE -komento

Kun SQL-kysely ajetaan, kysely menee ensimmäiseksi nk. Plannerille, suunnittelijalle, joka määrittää mikä on optimaalisin tapa toteuttaa annetun 
SQL-syntaksin mukainen kysely tietokannassa (esimerkiksi milloin tulisi käyttää määriteltyjä indeksejä ja milloin hakea vain taulusta rivi kerrallaan),
ja muokkaa kyselyä sen mukaan.

Olet ehkä huomannutkin että kun ajat PgAdminissa kyselyn ruudussa käväisee vihreä palkki, joka kertoo kuinka monta tietuetta kysely palautti mutta
myös sen, kuinka kauan kyselyyn kului aikaa millisekunteina. Vaikka tästä arvosta saakin osviittaa kyselyn kestosta, se sisältää myös esimerkiksi 
verkkoliikenteeseen kuluvan ajan ja ei siten ole kovin sopiva itse kyselyjen optimointia tarkasteltaessa. Tähän tarkoitukseen on olemassa komennot 
EXPLAIN sekä EXPLAIN ANALYZE. Näitä käytetään yksinkertaisesti kirjoittamalla kyseinen avainsana ennen varsinaista kyselyä. Nämä kaksi eroavat toisistaan 
siinä, että EXPLAIN-komennolla saa näkyviin Plannerin muodostaman suunnitelman kyselyn toteutuksesta, kun taas EXPLAIN ANALYZE suorittaa kyselyn ja 
palauttaa lisäksi tietoa itse suorituksen kestosta. Kestosta annetaan sekä suunnitelman tuottamiseen kulunut aika että (käytettäessä EXPLAIN ANALYZEä)
sen suorittamiseen kuluva aika millisekunteina. Lisäksi kysely eri osien suhteellisia kustannuksia (Cost). On myös huomattava, että kumpikaan ei kuitenkaan 
palauta itse kyselyn tuottamia rivejä vaan ainoastaan tiedon siitä, millä tavoin kyselyä tultaisiin ajamaan.

Tarkastellaan tätä muutamien esimerkkikyselyiden avulla:

:::code-box
```sql

EXPLAIN ANALYZE SELECT * FROM helsinki.liikennevaylat;

```
:::


:::code-box
```sql

EXPLAIN ANALYZE SELECT * FROM helsinki.liikennevaylat WHERE pituus BETWEEN 50 AND 55;

```
:::

:::code-box
```sql

EXPLAIN ANALYZE SELECT * FROM helsinki.liikennevaylat WHERE pituus < 13;

```
:::

Luodaan sitten BTREE-indeksi kentälle "pituus". Lyhimmillään tämä käy komennolla

:::code-box
```sql

CREATE INDEX ON helsinki.liikennevaylat (pituus);

```
:::

Jos halutaan varmistua indeksin nimestä ja tyypistä, kirjoitetaan eksplisiittisesti

:::code-box
```sql

CREATE INDEX liikennevaylat_pituus_idx ON helsinki.liikennevaylat USING BTREE (pituus);

```
:::

Samaten indeksin poistaminen on helppoa:

:::code-box
```sql

DROP INDEX liikennevaylat_pituus_idx;

```
:::

Aja edellä annettuja kyselyjä ensin ilman indeksiä ja indeksin määrittelyn jälkeen (voit koittaa ajaa kyselyn muutaman kerran saadaksesi keskiarvon)







EXPLAIN ANALYZEn tuloksissa esiintyviä sanoja:
- Seq Scan = sequential scanning, taulusta haetaan rivi kerrallaan
- Bitmap Heap Scan
- Bitmap Index Scan
- Heap Blocks
- Hash Join =

cost 
row 
width
actual time
loops

Katso koko SELECT pg_size_pretty(pg_relation_size(‘users_username_idx’));

Muut työkalut: https://explain.depesz.com/, https://explain.dalibo.com/ voi käyttää myös lokaalisti käytettävä versio, html-tiedosto?
 

## PostgreSQL:n spatiaaliset indeksit