# Harjoitus 10: Suorituskyvyn optimointi

**Harjoituksen sisältö** - Tutustutaan aiheisiin PostgreSQL:n suorituskykyyn liittyen.

**Harjoituksen tavoite** - Opiskelija tietää mitkä tekijät ja parametrit vaikuttavat PostgreSQL-tietokannan suorituskykyyn ja miten niitä muutetaan.


## Harjoitus 9.1: Taulutilat

Tarkista koulutuspalvelimen oletustaulutilojen sijainti. Käyttäjien tiedot sijaitsevat **pg_default**-taulutilassa, joka on data_directoryn base-hakemistossa. Järjestelmän yleiset tiedot sijaitsevat **pg_global**-taulutilassa, joka on data_directoryn global-hakemistossa. Datahakemiston sijainnin voit tarkistaa komennolla:

:::code-box
```sql
SHOW data_directory;
```
:::


## Harjoitus 9.6: Tietokannan ja taulun taulutilan muuttaminen

Koko tietokannan taulutilan voi muuttaa yhdellä komennolla.

:::hint-box
**HUOM!** Tätä ei kuitenkaan voi tehdä jos tietokantaan on auki aktiivisia yhteyksiä!
:::

1. Sulje pgAdminin tietokantayhteys harjoitustietokantaasi klikkaamalla tietokantaa sivupaneelissa hiiren oikealla painikkeella ja valitsemalla **Disconnect Database**.
2. Avaa tämän jälkeen sivupaneelista postgres-tietokanta ja avaa **Query tool** (voit tehdä tämän myös psql:n avulla). Anna komento:

:::code-box
```sql
ALTER DATABASE trainingdatabase
SET TABLESPACE tmp_tablespace;
```
:::

:::hint-box
Mikäli tämä ei onnistu, ja pgAdmin4 kertoo, että tietokantaan on aktiivisia yhteyksiä, yritä kirjautua ulos ja takaisin sisään pgAdminiin.
:::

Voit tarkistaa tietokannan taulutilan sijainnin SQL-kyselyllä:

:::code-box
```sql
SELECT
spcname, pg_tablespace_location(oid)
FROM
pg_tablespace;
```
:::

Luo testausta varten tilapäinen taulu:

:::code-box
```sql
DROP TABLE IF EXISTS tmp_table;

CREATE TABLE tmp_table AS
SELECT x
FROM
generate_series(2,5000,2) AS x;
```
:::

Taulun käyttämän taulutilan voit tarkistaa seuraavalla komennolla:

:::code-box
```sql
SELECT
tablename, tablespace
FROM
pg_tables
WHERE
tablename = 'tmp_table';
```
:::

Muuta taulun taulutilaa seuraavalla komennolla:

:::code-box
```sql
ALTER TABLE
tmp_table
SET TABLESPACE
tmp_tablespace;
```
:::

Tarkista, että taulun taulutila on nyt muuttunut. Voit myös käyttää pgAdminin käyttöliittymää taulutilojen tarkastamiseen.

## Harjoitus 9.7: Indeksin taulutilan muuttaminen

Voit luoda indeksin tauluun komennolla:

:::code-box
```sql
CREATE INDEX
idx_tmp_x
ON tmp_table(x);
```
:::

Indeksit luodaan oletusarvoisesti **pg_default**-taulutilaan. Usein käytetyt indeksit voi olla tarpeen tallentaa sellaiseen taulutilaan, joka käyttää palvelimessa olevaa nopeinta levyä (esimerkiksi SSD-levyt). Indeksien taulutilan muuttaminen onnistuu seuraavasti:

:::code-box
```sql
ALTER INDEX
idx_tmp_x
SET TABLESPACE
tmp_tablespace;
```
:::

